// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN_XnpqQqYyX5kDiGBKSnLAF1OQN9HVXU',
    appId: '1:671116588856:web:e85c17adc80d5aef0373cd',
    messagingSenderId: '671116588856',
    projectId: 'crash-project-cp',
    authDomain: 'crash-project-cp.firebaseapp.com',
    storageBucket: 'crash-project-cp.appspot.com',
    measurementId: 'G-LK0LXPPE51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnor1uzMwsEzxm1zJ7wObrK3ZoMunnWAs',
    appId: '1:671116588856:android:6d253b6f6f1260240373cd',
    messagingSenderId: '671116588856',
    projectId: 'crash-project-cp',
    storageBucket: 'crash-project-cp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtnWIVDfcWzqYUbQkurEoW0Qmrmf3esw',
    appId: '1:671116588856:ios:ac4296f721b188450373cd',
    messagingSenderId: '671116588856',
    projectId: 'crash-project-cp',
    storageBucket: 'crash-project-cp.appspot.com',
    iosBundleId: 'com.Shade.crashDetectionAndAnalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtnWIVDfcWzqYUbQkurEoW0Qmrmf3esw',
    appId: '1:671116588856:ios:9f74bef8826792a30373cd',
    messagingSenderId: '671116588856',
    projectId: 'crash-project-cp',
    storageBucket: 'crash-project-cp.appspot.com',
    iosBundleId: 'com.Shade.crashDetectionAndAnalysis.RunnerTests',
  );
}
